[tool.poetry]
name = "testcloudbuild"
version = "0.1.0"
description = ""
authors = ["tactik8 <admin@tactik8.com>"]

[tool.poetry.dependencies]
python = "^3.8"
flask = "^1.1"

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
